version: '3'
services:
  grafana:
    container_name: grafana
    restart: unless-stopped
    image: my-grafana
    build:
      context: grafana-container
    user: root
    volumes:
      - grafana-data:/var/lib/grafana
    links:
      - prometheus
    ports:
      - "3000:3000"

  prometheus:
    container_name: prometheus
    restart: unless-stopped
    image: my-prometheus
    build:
      context: prometheus-container
    ports:
      - "9090:9090"

  srv:
    container_name: srv
    restart: unless-stopped
    image: songs_srv
    build:
      context: .
    environment:
      DB_USER: bo_dev
      DB_PASSWORD: pass12345
      DB_NAME: songs
      DB_PORT: 3307
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    container_name: db
    image: songs_db
    build:
      context: ./DB-container
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_USER: bo_dev
      MYSQL_PASSWORD: pass12345
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: songs
    ports:
      - "3307:3306"

#  test:
#    container_name: test
#    image: test_app
#    build:
#      context: ./tests
#    depends_on:
#      - srv
#      - db
volumes:
  mysql-data:
    driver: local
  grafana-data:
    driver: local